# Generated by Django 2.2.6 on 2019-10-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0003_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
