# Generated by Django 2.2.6 on 2019-10-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0004_auto_20191011_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='address_street',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='address_number',
        ),
    ]
