# Generated by Django 2.2.6 on 2019-10-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0006_auto_20191017_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='type_of',
            field=models.IntegerField(choices=[(1, 'fundacja'), (2, 'organizacja pozarządowa'), (3, 'zbiórka lokalna')], default=1),
        ),
    ]
