# Generated by Django 2.2.6 on 2019-10-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charity', '0007_auto_20191017_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(default='123-456-789', max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='institution',
            name='type_of',
            field=models.IntegerField(choices=[(1, 'Fundacja'), (2, 'Organizacja pozarządowa'), (3, 'Zbiórka lokalna')], default=1),
        ),
    ]
